export const ROUTES = {
    HOME: 'HOME',
    HOME_TAB: 'Home',
    SPLASH: 'SPLASH',
    LOGIN: 'LOGIN',
    ME_TAB: 'Me',
    ONBOARDING: 'ONBOARDING',
    EDIT_INFORMATION: 'EDIT_INFOMATION',
    LIST_VIDEO: 'LIST_VIDEO',
    STEP: 'STEP',
    SLEEPTRACKING: 'SLEEPTRACKING',
    HEART: 'HEART',
    WEATHER: 'WEATHER_SCREEN'
}